# Generated by Django 5.0.3 on 2024-03-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posiciones',
            fields=[
                ('id_pos', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_pos', models.CharField(max_length=40, verbose_name='Nombre Posición')),
                ('des_pos', models.TextField(verbose_name='Descripción Posición')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
                'db_table': 'posiciones',
            },
        ),
    ]
