# Generated by Django 5.0.3 on 2024-03-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_equipo', models.CharField(max_length=100, verbose_name='Equipo')),
                ('des_equipo', models.TextField(verbose_name='Descripción Equipo')),
                ('ban_equipo', models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d')),
                ('esc_equipo', models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
            },
        ),
    ]
