# Generated by Django 5.0.3 on 2024-03-10 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0002_equipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id_tecnico', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_tec', models.CharField(max_length=100, verbose_name='Nombre Técnico')),
                ('apll_tec', models.CharField(max_length=100, verbose_name='Apellido Técnico')),
                ('fecha_nac_tec', models.DateField()),
                ('nacionalidad_tec', models.CharField(max_length=100, verbose_name='Nacionalidad Técnico')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.equipos')),
            ],
            options={
                'verbose_name': 'Tecnico',
                'verbose_name_plural': 'Tecnicos',
                'db_table': 'tecnicos',
            },
        ),
    ]
