# Generated by Django 5.0.3 on 2024-03-10 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0003_tecnicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id_jugador', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_jug', models.CharField(max_length=100, verbose_name='Nombre Jugador')),
                ('apll_jug', models.CharField(max_length=100, verbose_name='Apellido Jugador')),
                ('foto_jug', models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d')),
                ('edad_jug', models.IntegerField()),
                ('fecha_nac_jug', models.DateField()),
                ('num_cams', models.IntegerField()),
                ('titular', models.BooleanField(default=True, verbose_name='Titular Sí')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.equipos', verbose_name='Equipo Jugador')),
                ('id_posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.posiciones', verbose_name='Posicion Jugador')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'Jugadores',
            },
        ),
    ]
