# Generated by Django 5.0.3 on 2024-03-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0004_jugadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='ban_equipo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='media/'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='esc_equipo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='media/'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='foto_jug',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
