# Generated by Django 5.0.3 on 2024-03-11 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0005_alter_equipos_ban_equipo_alter_equipos_esc_equipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipos',
            options={'verbose_name': 'Equipos', 'verbose_name_plural': 'Equipo'},
        ),
        migrations.AlterModelOptions(
            name='jugadores',
            options={'verbose_name': 'Jugadores', 'verbose_name_plural': 'Jugador'},
        ),
        migrations.AlterModelOptions(
            name='posiciones',
            options={'verbose_name': 'Posiciones', 'verbose_name_plural': 'Posición'},
        ),
        migrations.AlterModelOptions(
            name='tecnicos',
            options={'verbose_name': 'Tecnicos', 'verbose_name_plural': 'Tecnico'},
        ),
        migrations.AddField(
            model_name='tecnicos',
            name='rol_tec',
            field=models.CharField(choices=[('Técnico', 'Técnico'), ('Asistente', 'Asistente'), ('Médico', 'Médico'), ('Preparador', 'Preparador')], help_text='Seleccione el rol', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='ban_equipo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Bandera'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='esc_equipo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Escudo'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='id_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppAdmin.equipos', verbose_name='Equipo Jugador'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='id_posicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppAdmin.posiciones', verbose_name='Posicion Jugador'),
        ),
        migrations.AlterField(
            model_name='tecnicos',
            name='id_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppAdmin.equipos'),
        ),
    ]
